{% set name = "lseg-data" %}
{% set version = "2.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/lseg-data/lseg_data-{{ version }}.tar.gz
  sha256: 67f126b5132c8d6e00d51542baf88654ba21199252d841c7b1e28b20f09d8d62

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - appdirs >=1.4.4,<2
    - pyee >=9.0.4,<=12.0.0
    - httpx >=0.18.0,<0.28
    - httpcore <1.1.0
    - numpy
    - pandas >=2.0,<3.0
    - python-dateutil
    - requests
    - scipy
    - tenacity
    - watchdog
    - websocket-client >=1.5,!=1.5.0,!=1.5.2
    - pyhumps >=3.0.2,<4.0.0
    - jinja2 >=3.0.3,<4.0.0
    - simplejson

test:
  requires:
    - pip
  imports:
    - lseg.data
  commands:
    - pip check

about:
  home: https://developers.lseg.com/en/api-catalog/lseg-data-platform/lseg-data-library-for-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Client library for LSEG Data Platform APIs
  description: |
    The LSEG Data Library for Python provides a simplified interface for accessing LSEG Data
    Platform content including real-time streaming data, historical data, news, and reference
    data from the London Stock Exchange Group.
  dev_url: https://github.com/LSEG-API-Samples/Example.DataLibrary.Python
  doc_url: https://developers.lseg.com/en/api-catalog/lseg-data-platform/lseg-data-library-for-python

extra:
  anaconda-services:
    ref:
      - https://anaconda.zendesk.com/agent/tickets/109074
  recipe-maintainers:
    - amaloney
